### PR TITLE
Chore: Adding Black + Flake8 Linters 

### PR DESCRIPTION
**Pull request by guanjieshen**
**_Why:_**
Standardize linters and code quality check for Python code within the repo. 

Leveraging Black and Flake8 (however this is up for discussion on if it's something the team would want to adopt.)

**_What :_**
- Added 'black` linter check into the github actions workflow
- Added 'flake8` linter check into the github actions workflow

**_Next Steps:_**
- Run `black python` on the Python directory to format all code according to Black style guide. This can be done incrementally for PR readability

- Fix `flake8` violations or add them to the exclusion list.

**_Additional Details:_**
To run flake8 locally use `flake8 python --config python/.flake8`.
To run black locally use `black python`

**_Additional Considerations:_**

Right now there's are still a lot of flake8 rule violations. We can choose which ones we want to address or ignore. Up for suggestions :) For now, to skip flake8 checks for a specific row we can just add the following:

```python
# flake8: noqa: F821
dbutils.fs.ls("/")
```

To skip a certain rule globally, we can add it to the `extend-ignore` list in the `.flake8` folder.

I am finding that Black does not do a good job with long arrays and forcibly wraps them; thereby making it difficult to read. This issue does not appear like it will be address by the Black team moving forward https://github.com/psf/black/issues/1281. 

For example, Black turns the following:
```python
        expected_data = [
            ["S1", "2020-08-01 00:00:10", 349.21, "2020-08-01 00:00:01", 345.11, 351.12],
            ["S1", "2020-08-01 00:01:12", 351.32, "2020-08-01 00:01:05", 348.10, 353.13],
```
into
```python
    expected_data = [
        [
            "S1",
            "2020-08-01 00:00:10",
            349.21,
            "2020-08-01 00:00:01",
            345.11,
            351.12,
        ],
        [
            "S1",
            "2020-08-01 00:01:12",
            351.32,
            "2020-08-01 00:01:05",
            348.10,
            353.13,
        ],
```
For readability sake, if there's an array were we want to ignore black formatting rules we can just skip the linter check e.g.

```python
        # fmt: off
        expected_data = [
                ["S1", "2020-08-01 00:00:10", 349.21, "2020-08-01 00:00:01", 345.11, 351.12],
                ["S1", "2020-08-01 00:01:12", 351.32, "2020-08-01 00:01:05", 348.10, 353.13],
                ["S1", "2020-09-01 00:02:10", 361.1, "2020-09-01 00:02:01", 358.93, 365.12],
                ["S1", "2020-09-01 00:19:12", 362.1, "2020-09-01 00:15:01", 359.21, 365.31]]
        # fmt: on
```

### CODE REVIEW

**Comment by guanjieshen** [comment]
11 files would be reformatted, 6 files would be left unchanged.

**Comment by guanjieshen** [comment]
This PR only adds the linting checks to the Github actions workflow. We can apply the actual linting changes in a layer approach in subsequent PRs.

**Comment by guanjieshen** [comment]
Hmm I don't know why the diffs are still showing up for `tsdf.py` and `interpolate.py`

**Review by tnixon — APPROVED** [review]
Looks good!

**Pull request merged**
