### PR TITLE
tempo automatic pypi version upgrader

### PR DESCRIPTION
**Pull request by souvik-databricks**
Added a libversioner utility which automatically gets an updated build version number.

### CODE REVIEW

**Review by rportilla-databricks — CHANGES_REQUESTED** [review]
This looks good - but is there a way we can test this out using test pypi?

**Comment by souvik-databricks** [comment]
Yes @rportilla-databricks we can test it on a deployment to TestPyPI server also. I have the testpypi server's endpoint with me. 
I am making a push to the function with this _environment as a parameter_. And the _json api endpoint will automatically be picked based on whether we are deploying_ to: 
* **_testpypi_** 
or
* _**pypi**_

**Comment by souvik-databricks** [comment]
@rportilla-databricks Now, I have pushed the change, it can be tested against TestPyPI server. 
However, let's keep this PR on hold and not complete yet. 
I need to discuss with @tnixon and come to a conclusion, as I think his approach can handle both git releases and the setup.py

**Comment by souvik-databricks** [comment]
@rportilla-databricks  
I am removing this PR as after my discussion with @tnixon, we have decided that this approach is not in line with our development pattern.

**Pull request closed without merging**
