### PR TITLE
Implement show and other data-preview methods on TSDF and also select method for TSDF similar to normal Dataframes

### LINKED ISSUE #60: Implement `show` and other data-preview methods on TSDF
As a convenience, we should have `show` and other data-preview methods available directly on TSDF

### PR DESCRIPTION
**Pull request by Spratiher9**
Adding the *standard data previewing* functions for TSDF object 
* show()
* display()

The functions are implemented with their behaviour based on the environment they are being called from, namely, DATABRICKS, JUPYTER_NOTEBOOK or any other python repl or script

resolves #60

### CODE REVIEW

**Comment by Spratiher9** [comment]
@rportilla-databricks Let me know after your review. Once this PR is completed I will raise a separate PR for 

Issue No 93 Support Waterfall join. I don't want to push it now as this PR is only for issue #95 alone

**Comment by rportilla-databricks** [comment]
@Spratiher9 sure. I pushed a change which was causing failures in an integration test. I may need to update the requirements and test this as well.

**Comment by rportilla-databricks** [comment]
@Spratiher9 , could you screenshot a code sample for an integration test of this in a Databricks environment? Based on my runtime, the display command is not working, likely due to conflicts. If it doesn't work in Databricks, we may need to remove.

**Comment by Spratiher9** [comment]
Sure @rportilla-databricks  let me run that display method on databricks once and I will share the screenshot of the same here.

**Comment by Spratiher9** [comment]
@rportilla-databricks 

Ricardo, I ran the function in my DB workspace, it worked perfectly attaching screenshots and the notebook for your reference.

- *With runtime* **7.3 LTS** 
      * image

- *With runtime* **10.0**
      * image

Here is the Notebook also in the ZIP file as the databricks notebooks HTML is not allowed to attach in the comment.
[Test of display on databricks from user_ns.zip](https://github.com/databrickslabs/tempo/files/7446779/Test.of.display.on.databricks.from.user_ns.zip)

**Comment by Spratiher9** [comment]
Let me know @rportilla-databricks if you want me to build a wheel and test also.

**Comment by rportilla-databricks** [comment]
The test with built code would be a good baseline. Here's what I'm using: 

%pip install -e git+https://github.com/Spratiher9/tempo.git#"egg=dbl-tempo&#subdirectory=python"

**Comment by Spratiher9** [comment]
@rportilla-databricks Got it. Let me run this test by building the wheel.

**Comment by Spratiher9** [comment]
@rportilla-databricks 
Ricardo, I have solved the functional issue with the `display` method. But now I am getting a cyclic dependency issue. I am working on fixing it.

**Comment by Spratiher9** [comment]
@rportilla-databricks  Ricardo, its fixed and I have done the integrated testing with the wheel file also now it's working. You can go ahead and do the review.

Here's the Notebook: [Tempo build test notebook](https://github.com/Spratiher9/Files/blob/master/Tempo%20build%20test.html)

Screenshot:

image

**Comment by rportilla-databricks** [comment]
@Spratiher9 this looks great now. Just 2 comments: 

1) I think it's worth testing this in at least one other non-notebook environment (e.g EMR). Let me know if you can do that - if not, I can spin something up.
2) Could you update the README (in the Python folder and top level) to show this new feature? It's a very nice ease-of-use feature to showcase as the first method to try. 

Thanks!

**Comment by Spratiher9** [comment]
Hi @rportilla-databricks 

So I don't have access to any such environment like Dataproc or EMR. But I tested it in other environments like Kaggle Notebooks. The library worked as expected.

Screenshot:
* Kaggle Notebook usage
  Kaggle

I have made the changes in the README files also. 

Kindly run the test on EMR and let me know in case any exception handling or something is required from my side over there.

**Comment by Spratiher9** [comment]
@rportilla-databricks 

On a different note Ricardo while editing the README files I saw this snippet of code:

```python
moving_avg = watch_accel_tsdf.withRangeStats("y", rangeBackWindowSecs=600).df
moving_avg.select('event_ts', 'x', 'y', 'z', 'mean_y').show(10, False)
```

So, I am introducing an implementation of the select method for TSDF also in the pull request.

**Comment by Spratiher9** [comment]
@rportilla-databricks 
Ricardo the select statement is also working as expected.

image

So I am changing the README with the select statement's usage also in the code snippet that I cited in my earlier comment

**Comment by rportilla-databricks** [comment]
@Spratiher9 sounds good. For the select, above I see a strange suite of characters - can we remove that from the message? Also, can you please use the logger (this is in tempo already) - there should be no print statements. After those are in, I will merge.

**Comment by Spratiher9** [comment]
@rportilla-databricks 

I have removed 🥺 the `flip the table` character art from the messages and added the logger as you suggested.

**Review by rportilla-databricks — APPROVED** [review]

**Pull request merged**
