### PR TITLE
removed old deprecated scala code

### LINKED ISSUE #306: Deprecate & remove Scala code
The Scala implementation of Tempo is out of date and not maintained. We should remove it from current versions of the repo and documentation as it is causing confusion for users.

### PR DESCRIPTION
**Pull request by tnixon**
This closes #306

### CODE REVIEW

**Review by R7L208 — APPROVED** [review]
LGTM

**Review by souvik-databricks — COMMENTED** [review]
Everything looks okay to me. 

Just one thing. I think we need to add a line in the sphinx documentation mentioning that the scala package is no longer supported going forward.

**Review by rportilla-databricks — APPROVED** [review]
We might want at banner on the top-level README (

**Review by souvik-databricks — APPROVED** [review]
Looks good to me now.

**Pull request merged**
