### PR TITLE
[BUG] Adding the pandas dataframe import

### PR DESCRIPTION
**Pull request by Spratiher9**
Adding the pandas dataframe import statement otherwise display_html the display method for pandas dataframes will not work and raise NameNotFoundError.

### CODE REVIEW

**Comment by rportilla-databricks** [comment]
@Spratiher9 , could you add a unit test for this?

**Comment by Spratiher9** [comment]
Sure @rportilla-databricks 
I will add the unit test for this on Thursday when I am back.

**Comment by Spratiher9** [comment]
@rportilla-databricks 

I have added the unit test for the display variable being called correctly or not Ricardo 
Let me know in case if any change is required.

**Comment by rportilla-databricks** [comment]
@Spratiher9 could you open up access of your branch to me? I just have a couple updates.

**Comment by Spratiher9** [comment]
@rportilla-databricks 

Hi Ricardo,
I have allowed edit by maintainers. 

image

Let me know if that is giving enough permission to you. 
I have edited two files only

* In utils.py I have added one import statement 
  image

* In tests.py I have added one extra test
  image

**Comment by rportilla-databricks** [comment]
Thank you. Was this file tested? The test doesn't run in my env - I may be missing a dependency. 

image

**Comment by rportilla-databricks** [comment]
Committed the updated import. Note that this also requires pandas/ipython (not previously true), so those have been updated in the setup.py. Thanks @Spratiher9!

**Review by rportilla-databricks — APPROVED** [review]
changes look good now.

**Pull request merged**
